project_name: oatmeal
builds:
  - main: ./tools/goreleaser.go
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    hooks:
      post: ./tools/goreleaser-dist.sh {{ .Target }}
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
archives:
  - format_overrides:
    - goos: windows
      format: zip
    files:
      - completions/*
      - LICENSE
      - THIRDPARTY.html

signs:
  - artifacts: checksum
    args: ["-u", "6A34CFEE77FE8257C3BB92FE24C3FC5D6987904B", "--output", "${signature}", "--detach-sign", "${artifact}"]

brews:
  - repository:
      owner: dustinblackman
      name: homebrew-tap
    folder: Formula
    homepage: https://github.com/dustinblackman/oatmeal
    description: Terminal UI to chat with large language models (LLM) using backends such as Ollama, and direct integrations with your favourite editor like Neovim!
    test: |
      system "#{bin}/oatmeal --version"
    extra_install: |-
      bash_completion.install "completions/oatmeal.bash" => "oatmeal"
      zsh_completion.install "completions/oatmeal.zsh" => "_oatmeal"
      fish_completion.install "completions/oatmeal.fish"

scoops:
- repository:
    owner: dustinblackman
    name: scoop-bucket
  homepage: https://github.com/dustinblackman/oatmeal
  description: Terminal UI to chat with large language models (LLM) using backends such as Ollama, and direct integrations with your favourite editor like Neovim!
  license: MIT

nfpms:
  - homepage: https://github.com/dustinblackman/oatmeal
    description: Terminal UI to chat with large language models (LLM) using backends such as Ollama, and direct integrations with your favourite editor like Neovim!
    maintainer: Dustin Blackman
    vendor: Dustin Blackman
    formats:
      - deb
      - rpm
    contents:
      - src: ./completions/oatmeal.bash
        dst: /usr/share/bash-completion/completions/oatmeal
        file_info:
          mode: 0644
      - src: ./completions/oatmeal.fish
        dst: /usr/share/fish/completions/oatmeal.fish
        file_info:
          mode: 0644
      - src: ./completions/oatmeal.zsh
        dst:  /usr/share/zsh/vendor-completions/_oatmeal
        file_info:
          mode: 0644
      - src: ./LICENSE
        dst: /usr/share/doc/oatmeal/copyright/LICENSE
        file_info:
          mode: 0644
      - src: ./THIRDPARTY.html
        dst: /usr/share/doc/oatmeal/copyright/THIRDPARTY.html
        file_info:
          mode: 0644

aurs:
  - name: oatmeal-bin
    homepage: https://github.com/dustinblackman/oatmeal
    description: Terminal UI to chat with large language models (LLM) using backends such as Ollama, and direct integrations with your favourite editor like Neovim!
    maintainers:
      - "Dustin Blackman"
    contributors:
      - "Dustin Blackman"
    license: "MIT"
    private_key: "{{ .Env.AUR_KEY }}"
    git_url: "ssh://aur@aur.archlinux.org/oatmeal-bin.git"
    package: |-
        # bin
        install -Dm755 "./oatmeal" "${pkgdir}/usr/bin/oatmeal"

        # license
        install -Dm644 "./LICENSE" "${pkgdir}/usr/share/licenses/oatmeal/LICENSE"
        install -Dm644 "./THIRDPARTY.html" "${pkgdir}/usr/share/licenses/oatmeal/THIRDPARTY.html"

        # completions
        mkdir -p "${pkgdir}/usr/share/bash-completion/completions/"
        mkdir -p "${pkgdir}/usr/share/zsh/site-functions/"
        mkdir -p "${pkgdir}/usr/share/fish/vendor_completions.d/"
        install -Dm644 "./completions/oatmeal.bash" "${pkgdir}/usr/share/bash-completion/completions/oatmeal"
        install -Dm644 "./completions/oatmeal.zsh" "${pkgdir}/usr/share/zsh/site-functions/_oatmeal"
        install -Dm644 "./completions/oatmeal.fish" "${pkgdir}/usr/share/fish/vendor_completions.d/oatmeal.fish"

changelog:
  use: github-native
