project_name: oatmeal
changelog:
  use: github-native

builds:
  - main: ./tools/goreleaser.go
    id: default
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    hooks:
      post: ./tools/goreleaser-dist.sh default {{ .Target }}
  - main: ./tools/goreleaser.go
    id: musl
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    hooks:
      post: ./tools/goreleaser-dist.sh musl {{ .Target }}

checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"

archives:
  - builds:
      - default
    format_overrides:
      - goos: windows
        format: zip
    <<: &archive_defaults
      files:
        - completions/*
        - manpages/*
        - LICENSE
        - THIRDPARTY.html

  - id: musl
    builds:
      - musl
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}-musl_
      {{- if eq .Arch "amd64" }}amd64
      {{- else }}{{ .Arch }}{{ end }}
    <<: *archive_defaults

signs:
  - artifacts: checksum
    args:
      [
        "-u",
        "2C3F6542F953A9E825E0FDFE8EF35FED51652BF5",
        "--output",
        "${signature}",
        "--detach-sign",
        "${artifact}"
      ]

brews:
  - ids:
      - default
    repository:
      owner: dustinblackman
      name: homebrew-tap
    folder: Formula
    homepage: https://github.com/dustinblackman/oatmeal
    description: Terminal UI to chat with large language models (LLM) using backends such as Ollama, and direct integrations with your favourite editor like Neovim!
    test: |
      system "#{bin}/oatmeal --version"
    extra_install: |-
      bash_completion.install "completions/oatmeal.bash" => "oatmeal"
      zsh_completion.install "completions/oatmeal.zsh" => "_oatmeal"
      fish_completion.install "completions/oatmeal.fish"
      man1.install "manpages/oatmeal.1.gz"

scoops:
  - repository:
      owner: dustinblackman
      name: scoop-bucket
    homepage: https://github.com/dustinblackman/oatmeal
    description: Terminal UI to chat with large language models (LLM) using backends such as Ollama, and direct integrations with your favourite editor like Neovim!
    license: MIT

nfpms:
  - builds:
      - default
    formats:
      - deb
      - rpm
    rpm:
      signature:
        key_file: "{{ .Env.RPM_KEY }}"
    <<: &nfpms_defaults
      homepage: https://github.com/dustinblackman/oatmeal
      description: Terminal UI to chat with large language models (LLM) using backends such as Ollama, and direct integrations with your favourite editor like Neovim!
      maintainer: Dustin Blackman
      vendor: Dustin Blackman
      contents:
        - src: ./completions/oatmeal.bash
          dst: /usr/share/bash-completion/completions/oatmeal
          file_info:
            mode: 0644
        - src: ./completions/oatmeal.fish
          dst: /usr/share/fish/completions/oatmeal.fish
          file_info:
            mode: 0644
        - src: ./completions/oatmeal.zsh
          dst: /usr/share/zsh/vendor-completions/_oatmeal
          file_info:
            mode: 0644
        - src: ./manpages/oatmeal.1.gz
          dst: /usr/share/man/man1/oatmeal.1.gz
          file_info:
            mode: 0644
        - src: ./LICENSE
          dst: /usr/share/doc/oatmeal/copyright/LICENSE
          file_info:
            mode: 0644
        - src: ./THIRDPARTY.html
          dst: /usr/share/doc/oatmeal/copyright/THIRDPARTY.html
          file_info:
            mode: 0644

  - builds:
      - musl
    id: musl
    formats:
      - apk
    <<: *nfpms_defaults

aurs:
  - ids:
      - default
    name: oatmeal-bin
    homepage: https://github.com/dustinblackman/oatmeal
    description: Terminal UI to chat with large language models (LLM) using backends such as Ollama, and direct integrations with your favourite editor like Neovim!
    maintainers:
      - "Dustin Blackman"
    contributors:
      - "Dustin Blackman"
    license: "MIT"
    private_key: "{{ .Env.AUR_KEY }}"
    git_url: "ssh://aur@aur.archlinux.org/oatmeal-bin.git"
    package: |-
      # bin
      install -Dm755 "./oatmeal" "${pkgdir}/usr/bin/oatmeal"

      # license
      install -Dm644 "./LICENSE" "${pkgdir}/usr/share/licenses/oatmeal/LICENSE"
      install -Dm644 "./THIRDPARTY.html" "${pkgdir}/usr/share/licenses/oatmeal/THIRDPARTY.html"

      # completions
      mkdir -p "${pkgdir}/usr/share/bash-completion/completions/"
      mkdir -p "${pkgdir}/usr/share/zsh/site-functions/"
      mkdir -p "${pkgdir}/usr/share/fish/vendor_completions.d/"
      install -Dm644 "./completions/oatmeal.bash" "${pkgdir}/usr/share/bash-completion/completions/oatmeal"
      install -Dm644 "./completions/oatmeal.zsh" "${pkgdir}/usr/share/zsh/site-functions/_oatmeal"
      install -Dm644 "./completions/oatmeal.fish" "${pkgdir}/usr/share/fish/vendor_completions.d/oatmeal.fish"

      # man pages
      install -Dm644 "./manpages/oatmeal.1.gz" "${pkgdir}/usr/share/man/man1/oatmeal.1.gz"

nix:
  - name: oatmeal
    ids:
      - default
    repository:
      owner: dustinblackman
      name: nur-packages
    skip_upload: true
    homepage: https://github.com/dustinblackman/oatmeal
    description: Terminal UI to chat with large language models (LLM) using backends such as Ollama, and direct integrations with your favourite editor like Neovim!
    path: pkgs/oatmeal.nix
    license: mit
    extra_install: |-
      patchelf --set-interpreter $(cat $NIX_CC/nix-support/dynamic-linker) $out/bin/oatmeal

      mkdir -p $out/share/doc/oatmeal/copyright
      cp LICENSE $out/share/doc/oatmeal/copyright/
      cp THIRDPARTY.html $out/share/doc/oatmeal/copyright/

      installManPage ./manpages/oatmeal.1.gz
      installShellCompletion ./completions/*

winget:
  - name: oatmeal
    publisher: dustinblackman
    license: MIT
    homepage: https://github.com/dustinblackman/oatmeal
    license_url: https://github.com/dustinblackman/oatmeal/blob/main/LICENSE
    copyright_url: https://github.com/dustinblackman/oatmeal/blob/main/LICENSE
    release_notes_url: https://github.com/dustinblackman/oatmeal/blob/main/CHANGELOG.md
    short_description: Terminal UI to chat with large language models (LLM) using backends such as Ollama, and direct integrations with your favourite editor like Neovim!
    dependencies:
      - package_identifier: Microsoft.VCRedist.2015+.x64
    repository:
      owner: dustinblackman
      name: winget-pkgs
      branch: "dustinblackman-{{.Version}}"
      pull_request:
        enabled: true
        draft: true
        base:
          owner: microsoft
          name: winget-pkgs
          branch: master

dockers:
  - image_templates:
      - "ghcr.io/dustinblackman/oatmeal:v{{ .Version }}-amd64"
      - "ghcr.io/dustinblackman/oatmeal:latest-amd64"
    ids:
      - musl
    goarch: arm64
    dockerfile: Dockerfile
    use: buildx
    extra_files:
      - LICENSE
      - THIRDPARTY.html
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--builder=desktop-linux"
      - "--label=io.artifacthub.package.readme-url=https://raw.githubusercontent.com/dustinblackman/oatmeal/main/README.md"
      - "--label=io.artifacthub.package.license=MIT"
      - "--label=org.opencontainers.image.description=Terminal UI to chat with large language models (LLM) using backends such as Ollama, and direct integrations with your favourite editor like Neovim!"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"

  - image_templates:
      - "ghcr.io/dustinblackman/oatmeal:v{{ .Version }}-arm64"
      - "ghcr.io/dustinblackman/oatmeal:latest-arm64"
    ids:
      - musl
    goarch: arm64
    dockerfile: Dockerfile
    use: buildx
    extra_files:
      - LICENSE
      - THIRDPARTY.html
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--builder=desktop-linux"
      - "--label=io.artifacthub.package.readme-url=https://raw.githubusercontent.com/dustinblackman/oatmeal/main/README.md"
      - "--label=io.artifacthub.package.license=MIT"
      - "--label=org.opencontainers.image.description=Terminal UI to chat with large language models (LLM) using backends such as Ollama, and direct integrations with your favourite editor like Neovim!"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"

docker_manifests:
  - name_template: "ghcr.io/dustinblackman/oatmeal:v{{ .Version }}"
    image_templates:
      - "ghcr.io/dustinblackman/oatmeal:v{{ .Version }}-amd64"
      - "ghcr.io/dustinblackman/oatmeal:v{{ .Version }}-arm64"
  - name_template: "ghcr.io/dustinblackman/oatmeal:latest"
    image_templates:
      - "ghcr.io/dustinblackman/oatmeal:latest-amd64"
      - "ghcr.io/dustinblackman/oatmeal:latest-arm64"
