version: "3"
services:
  oatmeal:
    command: /bin/sh -c "trap :; TERM INT; sleep infinity & wait"
    image: ghcr.io/dustinblackman/devcontainer-oatmeal@sha256:a6945cd15ea4f8bb0d716db08feb5be1f5d22e3b5a26953234ee82531fe66457
    environment:
      OATMEAL_OLLAMA_URL: http://host.docker.internal:11434
    volumes:
      - ..:/workspace
      - cache_bin:/workspace/.bin
      - cache_target:/workspace/target
volumes:
  cache_bin:
  cache_target:
